// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbZL6RP9Wm2Ogv8eAi-Djn7xgrBUohoAo',
    appId: '1:244183698332:web:aeaf8c26b35b8e27cdd659',
    messagingSenderId: '244183698332',
    projectId: 'auth-example-with-riverpod',
    authDomain: 'auth-example-with-riverpod.firebaseapp.com',
    storageBucket: 'auth-example-with-riverpod.appspot.com',
    measurementId: 'G-X1FKSP3W4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJs1p7kpqGKRXDW38-ZuEiAXO7VtEFrJM',
    appId: '1:244183698332:android:90e32385cc950a1fcdd659',
    messagingSenderId: '244183698332',
    projectId: 'auth-example-with-riverpod',
    storageBucket: 'auth-example-with-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaJvqVj2h0N5dQROMhCmRfxLk_OU344Ew',
    appId: '1:244183698332:ios:ec6259d02e141238cdd659',
    messagingSenderId: '244183698332',
    projectId: 'auth-example-with-riverpod',
    storageBucket: 'auth-example-with-riverpod.appspot.com',
    iosClientId: '244183698332-v6ed1k02srm1o8hjl14htphjs5c49d79.apps.googleusercontent.com',
    iosBundleId: 'com.qaisothman.firebaseAuthRiverpodGoGouter',
  );
}
